const menu = [
    {
      id: 1,
      title: 'Pasta Carbonara',
      category: 'pasta',
      price: 15.99,
      img: './images/carbonara.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, `,
    },
    {
      id: 2,
      title: 'Risotto with Mushrooms',
      category: 'risotto',
      price: 13.99,
      img: './images/risotto.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, `,
    },
    {
      id: 3,
      title: 'Pizza Margherita',
      category: 'pizza',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    },
    // {
    //   id: 4,
    //   title: 'Pasta Bolognese',
    //   category: 'pasta',
    //   price: 20.99,
    //   img: './images/item-4.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    // },
    // {
    //   id: 5,
    //   title: 'Risotto Sea FOOD',
    //   category: 'risotto',
    //   price: 22.99,
    //   img: './images/item-5.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, `,
    // },
    // {
    //   id: 6,
    //   title: 'Pizza Diavola',
    //   category: 'pizza',
    //   price: 18.99,
    //   img: './images/item-6.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    // },
    // {
    //   id: 7,
    //   title: 'Lasagna Bolognese',
    //   category: 'pasta',
    //   price: 18.99,
    //   img: './images/item-7.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, `,
    // },
    // {
    //   id: 8,
    //   title: 'Risotto',
    //   category: 'risotto',
    //   price: 12.99,
    //   img: './images/item-8.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,  `,
    // },
    // {
    //   id: 9,
    //   title: 'Pizza Quattro Stagioni ',
    //   category: 'pizza',
    //   price: 16.99,
    //   img: './images/item-9.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    // },
    // {
    //   id: 10,
    //   title: 'Pizza Quattro Formaggi',
    //   category: 'pizza',
    //   price: 16.99,
    //   img: './images/item-9.jpeg',
    //   desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,`,
    //   }
  ];
  export default menu;